install:
    pip install --upgrade pip &&\
        pip install - requirments.txt 

format:
    black *.py

lint
    pylint --disable=R,C hello.py

test:
    python -m pytest -vv --cov=hello testhello.py